version: '3.5'

services:
  nginx:
    image: nginx:1.17
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - nginx_www:/var/www
      - ${PUBLIC_DIR:-/var/togovar/public}:/var/www/public
      - app_sockets:/tmp/sockets
    ports:
      - ${NGINX_PORT:-80}:80
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "1"
    depends_on:
      - app
      - sparqlist
      - virtuoso
      - jbrowse
      - elasticsearch01
      - elasticsearch02
      - elasticsearch03
      - elasticsearch04
      - elasticsearch05

  app:
    build: docker/ruby
    image: togovar_app:${VERSION:-2020.07}
    env_file: togovar.env
    volumes:
      - ./app:/app
      - ./stanza:/usr/local/stanza
      - nginx_www:/var/www
      - ${PUBLIC_DIR:-/var/togovar/public}:/var/www/public
      - app_bundle:/usr/local/bundle
      - app_log:/app/log
      - app_node_modules:/app/node_modules
      - app_tmp:/app/tmp
      - app_sockets:/app/tmp/sockets
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "1"

  stanza:
    build: docker/stanza
    image: togovar_stanza:${VERSION:-2020.07}
    env_file: togovar.env
    volumes:
      - ./stanza:/stanza
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "1"

  jbrowse:
    build: docker/jbrowse
    image: togovar_jbrowse:${VERSION:-2020.07}
    env_file: togovar.env
    volumes:
      - ./docker/jbrowse/template/jbrowse_conf.json:/var/www/jbrowse_conf.json:ro
      - ${JBROWSE_VOLUMES_DATA:-/var/togovar/jbrowse}:/var/www/data
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "1"

  sparqlist:
    image: dbcls/sparqlist:snapshot-1f7dbc9
    env_file: togovar.env
    volumes:
      - ./sparqlist:/app/repository
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "1"

  virtuoso:
    image: openlink/virtuoso-opensource-7:7.2
    env_file: togovar.env
    volumes:
      - ./docker/virtuoso/bin:/usr/local/bin
      - ${VIRTUOSO_VOLUMES_LOAD:-/var/togovar/virtuoso/load}:/load:ro
      - ${VIRTUOSO_VOLUMES_DATA:-/var/togovar/virtuoso/data}:/data
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "1"

  elasticsearch01: &elasticsearch
    image: elasticsearch:7.13.0
    env_file: togovar.env
    environment:
      - node.name=node01
      - discovery.seed_hosts=elasticsearch02,elasticsearch03,elasticsearch04,elasticsearch05
    volumes:
      - ${ELASTICSEARCH_VOLUMES_01_DATA:-/var/togovar/elasticsearch/01/data}:/usr/share/elasticsearch/data
      - ${ELASTICSEARCH_VOLUMES_SNAPSHOT:-/var/togovar/elasticsearch/snapshot}:/usr/share/elasticsearch/snapshot
    ulimits:
      memlock:
        soft: -1
        hard: -1
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "1"

  elasticsearch02:
    <<: *elasticsearch
    env_file: togovar.env
    environment:
      - node.name=node02
      - discovery.seed_hosts=elasticsearch01,elasticsearch03,elasticsearch04,elasticsearch05
    volumes:
      - ${ELASTICSEARCH_VOLUMES_02_DATA:-/var/togovar/elasticsearch/02/data}:/usr/share/elasticsearch/data
      - ${ELASTICSEARCH_VOLUMES_SNAPSHOT:-/var/togovar/elasticsearch/snapshot}:/usr/share/elasticsearch/snapshot
    ports: []

  elasticsearch03:
    <<: *elasticsearch
    env_file: togovar.env
    environment:
      - node.name=node03
      - discovery.seed_hosts=elasticsearch01,elasticsearch02,elasticsearch04,elasticsearch05
    volumes:
      - ${ELASTICSEARCH_VOLUMES_03_DATA:-/var/togovar/elasticsearch/03/data}:/usr/share/elasticsearch/data
      - ${ELASTICSEARCH_VOLUMES_SNAPSHOT:-/var/togovar/elasticsearch/snapshot}:/usr/share/elasticsearch/snapshot
    ports: []

  elasticsearch04:
    <<: *elasticsearch
    env_file: togovar.env
    environment:
      - node.name=node04
      - discovery.seed_hosts=elasticsearch01,elasticsearch02,elasticsearch03,elasticsearch05
    volumes:
      - ${ELASTICSEARCH_VOLUMES_04_DATA:-/var/togovar/elasticsearch/04/data}:/usr/share/elasticsearch/data
      - ${ELASTICSEARCH_VOLUMES_SNAPSHOT:-/var/togovar/elasticsearch/snapshot}:/usr/share/elasticsearch/snapshot
    ports: []

  elasticsearch05:
    <<: *elasticsearch
    env_file: togovar.env
    environment:
      - node.name=node05
      - discovery.seed_hosts=elasticsearch01,elasticsearch02,elasticsearch03,elasticsearch04
    volumes:
      - ${ELASTICSEARCH_VOLUMES_05_DATA:-/var/togovar/elasticsearch/05/data}:/usr/share/elasticsearch/data
      - ${ELASTICSEARCH_VOLUMES_SNAPSHOT:-/var/togovar/elasticsearch/snapshot}:/usr/share/elasticsearch/snapshot
    ports: []

volumes:
  nginx_www:
    name: togovar_nginx_www_${VERSION:-2020.07}
    driver: local
  app_bundle:
    name: togovar_app_bundle_${VERSION:-2020.07}
    driver: local
  app_log:
    name: togovar_app_log_${VERSION:-2020.07}
    driver: local
  app_node_modules:
    name: togovar_app_node_modules_${VERSION:-2020.07}
    driver: local
  app_tmp:
    name: togovar_app_tmp_${VERSION:-2020.07}
    driver: local
  app_sockets:
    name: togovar_app_sockets_${VERSION:-2020.07}
    driver: local
